using Dramalord.Data;
using TaleWorlds.Localization;

namespace Dramalord.Notifications
{
    public static class DramalordTexts
    {
        public const string MCM_AUTONOMY = "{=Dramalord001}Autonomy";
        public const string MCM_AUTONOMY_WANDERERS = "{=Dramalord002}Wanderer Autonomy";
        public const string MCM_AUTONOMY_WANDERERS_INFO = "{=Dramalord003}Allow clanless Wanderers to interact with lords and other wanderers";
        public const string MCM_AUTONOMY_PLAYERCLAN = "{=Dramalord031}Player Clan Autonomy";
        public const string MCM_AUTONOMY_PLAYERCLAN_INFO = "{=Dramalord032}Allow heroes of your clan to interact with lords and other wanderers";
        public const string MCM_AUTONOMY_NOTABLES = "{=Dramalord050}Include Notables";
        public const string MCM_AUTONOMY_NOTABLES_INFO = "{=Dramalord051}Include Notables like Gang leaders in Dramalord AI";
        public const string MCM_AUTONOMY_APPROACH_PLAYER = "{=Dramalord023}Chance Approaching Player";
        public const string MCM_AUTONOMY_APPROACH_PLAYER_INFO = "{=Dramalord024}Chance that heroes approach the player for conversations";
        public const string MCM_AUTONOMY_GOSSIP_PLAYER = "{=Dramalord056}Chance Gossiping Player";
        public const string MCM_AUTONOMY_GOSSIP_PLAYER_INFO = "{=Dramalord057}Chance that heroes approach the player for spreading gossip";
        public const string MCM_HERO = "{=Dramalord004}Hero Setup";
        public const string MCM_HERO_MIN_ATTRACTION = "{=Dramalord005}Minimum Attraction";
        public const string MCM_HERO_MIN_ATTRACTION_INFO = "{=Dramalord006}Attraction score required for NPCs to consider others as attractive";
        public const string MCM_HERO_MIN_LOVE_DATE = "{=Dramalord019}Minimum Dating Love";
        public const string MCM_HERO_MIN_LOVE_DATE_INFO = "{=Dramalord020}Love points required to consider dating a hero";
        public const string MCM_HERO_MIN_LOVE_MARRIAGE = "{=Dramalord025}Minimum Marriage Love";
        public const string MCM_HERO_MIN_LOVE_MARRIAGE_INFO = "{=Dramalord026}Love points required for heroes to consider marrying another hero";
        public const string MCM_HERO_MIN_TRUST_FRIEND = "{=Dramalord046}Minimum Trust Friends";
        public const string MCM_HERO_MIN_TRUST_FRIEND_INFO = "{=Dramalord047}Trust points required to consider a hero a friend";
        public const string MCM_HERO_MAX_TRUST_ENEMY = "{=Dramalord066}Maximum Trust Enemies";
        public const string MCM_HERO_MAX_TRUST_ENEMY_INFO = "{=Dramalord067}Negative trust points required to consider a hero an enemy";
        public const string MCM_HERO_PREGNANCY_DURATION = "{=Dramalord015}Pregnancy Duration";
        public const string MCM_HERO_PREGNANCY_DURATION_INFO = "{=Dramalord016}How many days is a hero pregnant before giving birth";
        public const string MCM_HERO_PREGNANCY_CHANCE = "{=Dramalord017}Pregnancy Chance";
        public const string MCM_HERO_PREGNANCY_CHANCE_INFO = "{=Dramalord018}Chance a hero gets pregnant (only for Dramalord pregnancies)";
        public const string MCM_HERO_MAX_FERTILITY_AGE = "{=Dramalord052}Maximum Fertility Age";
        public const string MCM_HERO_MAX_FERTILITY_AGE_INFO = "{=Dramalord053}Maximum age a hero can get pregnant (only for Dramalord pregnancies)";
        public const string MCM_HERO_LOVE_DECAY_START = "{=Dramalord048}Love Decay Start Day";
        public const string MCM_HERO_LOVE_DECAY_START_INFO = "{=Dramalord049}Number of days lovers haven't seen each other needed to make love decay.";
        public const string MCM_LOGGING = "{=Dramalord007}Logging Setup";
        public const string MCM_LOGGING_RELATIONSHIP = "{=Dramalord008}Relationship Logs";
        public const string MCM_LOGGING_RELATIONSHIP_INFO = "{=Dramalord009}Show relationship changes in the logs";
        public const string MCM_LOGGING_TALKING = "{=Dramalord062}Talking Logs";
        public const string MCM_LOGGING_TALKING_INFO = "{=Dramalord063}Show friendly conversation events in the logs";
        public const string MCM_LOGGING_FLIRTING = "{=Dramalord060}Flirting Logs";
        public const string MCM_LOGGING_FLIRTING_INFO = "{=Dramalord061}Show flirting events in the logs";
        public const string MCM_LOGGING_DATING = "{=Dramalord058}Dating Logs";
        public const string MCM_LOGGING_DATING_INFO = "{=Dramalord059}Show dating events in the logs";
        public const string MCM_LOGGING_INTERCOURSE = "{=Dramalord064}Intercourse Logs";
        public const string MCM_LOGGING_INTERCOURSE_INFO = "{=Dramalord065}Show intercourse events in the logs";
        public const string MCM_LOGGING_IMPREGNATION = "{=Dramalord068}Impregnation Logs";
        public const string MCM_LOGGING_IMPREGNATION_INFO = "{=Dramalord069}Show impregnation events in the logs";
        public const string MCM_LOGGING_CHILDREN = "{=Dramalord013}Children Logs";
        public const string MCM_LOGGING_CHILDREN_INFO = "{=Dramalord014}Show birth, conceptions or orphanage events in the logs";
        public const string MCM_LOGGING_GOSSIP = "{=Dramalord391}Gossip Logs";
        public const string MCM_LOGGING_GOSSIP_INFO = "{=Dramalord392}Show when gossip is exchanged in the logs";
        public const string MCM_GENERAL = "{=Dramalord010}General";
        public const string MCM_GENERAL_CHANCE_CAUGHT = "{=Dramalord011}Chance of Getting Caught";
        public const string MCM_GENERAL_CHANCE_CAUGHT_INFO = "{=Dramalord012}Chance of getting caught by partners while interacting with other heroes";
        public const string MCM_GENERAL_PLAYER_ATTRACTION = "{=Dramalord021}Bonus Player Attraction";
        public const string MCM_GENERAL_PLAYER_ATTRACTION_INFO = "{=Dramalord022}Bonus value for player's attraction to other heroes";
        public const string MCM_GENERAL_PLAYER_SYMPATHY = "{=Dramalord029}Bonus Player Sympathy";
        public const string MCM_GENERAL_PLAYER_SYMPATHY_INFO = "{=Dramalord030}Bonus value for player's sympathy to other heroes";
        public const string MCM_GENERAL_INTERACTION_DELAY = "{=Dramalord027}Days Between Interactions";
        public const string MCM_GENERAL_INTERACTION_DELAY_INFO = "{=Dramalord028}Number of days heroes can't interact with the same hero again";
        public const string MCM_GENERAL_QUEST_CHANCE = "{=Dramalord041}Quest Chance";
        public const string MCM_GENERAL_QUEST_CHANCE_INFO = "{=Dramalord042}Chance that a lover of the player starts a quest";
        public const string MCM_GENERAL_DEFAULT_MARRIAGES = "{=Dramalord039}Allow Default Marriages.";
        public const string MCM_GENERAL_DEFAULT_MARRIAGES_INFO = "{=Dramalord040}Allow default marriages for all npcs";
        public const string MCM_GENERAL_DEFAULT_PREGNANCIES = "{=Dramalord037}Allow Default Pregnancies.";
        public const string MCM_GENERAL_DEFAULT_PREGNANCIES_INFO = "{=Dramalord038}Allow default pregnancies for all npcs";
        public const string MCM_GENERAL_ALLOW_INCEST = "{=Dramalord033}Allow Incest";
        public const string MCM_GENERAL_ALLOW_INCEST_INFO = "{=Dramalord034}Allow AI to approach family members for intimate and emotional events";
        public const string MCM_GENERAL_ALLOW_SAMESEX_MARRIAGE = "{=Dramalord035}Allow Same Sex Marriage";
        public const string MCM_GENERAL_ALLOW_SAMESEX_MARRIAGE_INFO = "{=Dramalord036}Allow AI to marry other heroes of the same sex (otherwise they are just lovers)";
        public const string MCM_GENERAL_ALLOW_CLASS_MIX = "{=Dramalord054}Allow Social Class Mix";
        public const string MCM_GENERAL_ALLOW_CLASS_MIX_INFO = "{=Dramalord055}Allow AI interactions between nobles and commoners (Lords and Notables/Wanderers)";
        public const string MCM_GENERAL_ALLOW_ORPHANAGE = "{=Dramalord423}Enable Dramalord Orphanage";
        public const string MCM_GENERAL_ALLOW_ORPHANAGE_INFO = "{=Dramalord424}If enabled NPC will put bastard children into the orphanage, otherwise they keep every child.";

        public const string MCM_OPTIONAL = "{=Dramalord043}Optional";
        public const string MCM_OPTIONAL_SHOW_RELATION_CHANGES = "{=Dramalord044}Show Relation Changes";
        public const string MCM_OPTIONAL_SHOW_RELATION_CHANGES_INFO = "{=Dramalord045}Enable this if you want to see relation change notifications (required for the Small Talk mod)";
        public const string MCM_OPTIONAL_SHOW_REAL_RELATIONS = "{=Dramalord070}Show Real Relation";
        public const string MCM_OPTIONAL_SHOW_REAL_RELATIONS_INFO = "{=Dramalord071}Enable this if you want to see the real relation to a hero (turn off if you're using True Noble Opinion)";
        public const string MCM_OPTIONAL_SHOW_HOTBUTTER = "{=Dramalord413}Use HotButter Animations";
        public const string MCM_OPTIONAL_SHOW_HOTBUTTER_INFO = "{=Dramalord414}Use HotButter animation for intimate scenes (will deactivate Dramalord animations).";
        public const string MCM_OPTIONAL_SHOW_DRAMALORD_VIDEOS = "{=Dramalord415}Show Dramalord Videos";
        public const string MCM_OPTIONAL_SHOW_DRAMALORD_VIDEOS_INFO = "{=Dramalord416}Show Dramalord videos for certain events. When turned off only text notifications will appear.";
        public const string MCM_OPTIONAL_SHOW_DRAMALORD_IMAGES = "{=Dramalord421}Show Dramalord Images";
        public const string MCM_OPTIONAL_SHOW_DRAMALORD_IMAGES_INFO = "{=Dramalord422}Show Dramalord images for certain events. When turned off only text notifications will appear.";

        public const string MCM_EDITOR_HERO = "{=Dramalord072}1: Hero Selection";
        public const string MCM_EDITOR_HERO_SELECT = "{=Dramalord073}Select Hero";
        public const string MCM_EDITOR_PERSONALITY = "{=Dramalord074}2: Personality";
        public const string MCM_EDITOR_DESIRE = "{=Dramalord075}3: Desire";
        public const string MCM_EDITOR_DESIRE_MEN = "{=Dramalord076}Attraction To Men";
        public const string MCM_EDITOR_DESIRE_WOMEN = "{=Dramalord077}Attraction To Women";
        public const string MCM_EDITOR_DESIRE_WEIGHT = "{=Dramalord078}Attraction To Weight";
        public const string MCM_EDITOR_DESIRE_BUILD = "{=Dramalord079}Attraction To Build";
        public const string MCM_EDITOR_DESIRE_AGE = "{=Dramalord080}Attraction To Age Difference";
        public const string MCM_EDITOR_DESIRE_LIBIDO = "{=Dramalord081}Libido";
        public const string MCM_EDITOR_DESIRE_LIBIDO_INFO = "{=Dramalord082}Defines whether an individual generally develops interest in intercourse or not";
        public const string MCM_EDITOR_DESIRE_AROUSAL_INFO = "{=Dramalord083}Represents how willing a hero currently is for intercourse due to hormones";
        public const string MCM_EDITOR_RELATION = "{=Dramalord084}4: Relation to Target";
        public const string MCM_EDITOR_RELATION_TARGET = "{=Dramalord085}Select Target";
        public const string MCM_EDITOR_RELATION_ATTRACTION = "{=Dramalord086}Current Attraction";
        public const string MCM_EDITOR_RELATION_SYMPATHY = "{=Dramalord087}Current Sympathy";

        public const string NAME_AROUSAL = "{=Dramalord222}Arousal";
        public const string NAME_TRUST = "{=Dramalord223}Trust";
        public const string NAME_LOVE = "{=Dramalord224}Love";
        public const string NAME_NO_RELATION = "{=Dramalord225}No Relationship";
        public const string NAME_FRIEND = "{=Dramalord226}Friend";
        public const string NAME_LOVER = "{=Dramalord227}Lover";
        public const string NAME_SPOUSE = "{=Dramalord228}Spouse";
        public const string NAME_ATTRACTION = "{=Dramalord229}Attraction";
        public const string NAME_SYMPATHY = "{=Dramalord230}Sympathy";
        public const string NAME_SEX_ORIENTATION = "{=Dramalord231}Sexual Orientation";
        public const string NAME_ASEXUAL = "{=Dramalord232}Asexual";
        public const string NAME_BISEXUAL = "{=Dramalord233}Bisexual";
        public const string NAME_HETEROSEXUAL = "{=Dramalord234}Heterosexual";
        public const string NAME_HOMOSEXUAL = "{=Dramalord235}Homosexual";
        public const string NAME_JEALOUSY = "{=Dramalord236}Jealousy";
        public const string NAME_EMPATHY = "{=Dramalord237}Empathy";
        public const string NAME_SOCIABILITY = "{=Dramalord238}Sociability";
        public const string NAME_BROTHER = "{=Dramalord245}brother";
        public const string NAME_SISTER = "{=Dramalord246}sister";
        public const string NAME_SON = "{=Dramalord247}son";
        public const string NAME_DAUGHTER = "{=Dramalord248}daughter";
        public const string NAME_HUSBAND = "{=Dramalord249}husband";
        public const string NAME_WIFE = "{=Dramalord250}wife";
        public const string NAME_YOUNGER = "{=Dramalord322}younger";
        public const string NAME_OLDER = "{=Dramalord323}older";
        public const string NAME_SAME_AGE = "{=Dramalord324}neither older nor younger";
        public const string NAME_MY_LOVER = "{=Dramalord343}my lover";
        public const string NAME_MY_LOVE = "{=Dramalord344}my love";
        public const string NAME_MY_SPOUSE = "{=Dramalord345}my spouse";
        public const string NAME_MY_FRIEND = "{=Dramalord346}my friend";
        public const string NAME_MY_ACQUAINTENCE = "{=Dramalord347}my acquaintance";


        public const string ENC_HERO_FAT_AND_STRONG = "{=Dramalord239}{ACTOR1.LINK} has a broad and heavyset physique.";
        public const string ENC_HERO_THIN_AND_STRONG = "{=Dramalord240}{ACTOR1.LINK} has a broad but lean physique.";
        public const string ENC_HERO_FAT_AND_WEAK = "{=Dramalord241}{ACTOR1.LINK} has a soft but heavyset physique.";
        public const string ENC_HERO_THIN_AND_WEAK = "{=Dramalord242}{ACTOR1.LINK} has a slender and lean physique.";
        public const string ENC_HERO_THIN = "{=Dramalord243}{ACTOR1.LINK} has a slender physique.";
        public const string ENC_HERO_WEAK = "{=Dramalord244}{ACTOR1.LINK} has a lean physique.";
        public const string ENC_HERO_STRONG = "{=Dramalord388}{ACTOR1.LINK} has a heavyset physique.";
        public const string ENC_HERO_FAT = "{=Dramalord389}{ACTOR1.LINK} has a broad physique.";

        public const string LOG_TALK_GOOD = "{=Dramalord167}{ACTOR1.LINK} was having a friendly chat with {ACTOR2.LINK}.";
        public const string LOG_TALK_BAD = "{=Dramalord168}{ACTOR1.LINK} was having an unpleasant chat with {ACTOR2.LINK}.";
        public const string LOG_FLIRT_GOOD = "{=Dramalord165}{ACTOR2.LINK} was smiling when {ACTOR1.LINK} flirted with them.";
        public const string LOG_FLIRT_BAD = "{=Dramalord166}{ACTOR2.LINK} was frowning when {ACTOR1.LINK} flirted with them.";
        public const string LOG_DATE_LOVE = "{=Dramalord164}{ACTOR1.LINK} and {ACTOR2.LINK} had an exciting date.";
        public const string LOG_DATE_FRIEND = "{=Dramalord163}{ACTOR1.LINK} and {ACTOR2.LINK} had a friendly date.";
        public const string LOG_DATE_BAD = "{=Dramalord162}{ACTOR1.LINK} and {ACTOR2.LINK} had a disappointing date.";
        public const string LOG_SEX_GOOD = "{=Dramalord170}{ACTOR1.LINK} was having satisfying intercourse with {ACTOR2.LINK}.";
        public const string LOG_SEX_BAD = "{=Dramalord169}{ACTOR1.LINK} was having intercourse with {ACTOR2.LINK}.";
        public const string LOG_CONCEIVE = "{=Dramalord171}{ACTOR1.LINK} was impregnated by {ACTOR2.LINK}.";
        public const string LOG_RElATIONSHIP_START = "{=Dramalord207}{ACTOR1.LINK} and {ACTOR2.LINK} are now {TEXT1}.";
        public const string LOG_RElATIONSHIP_END = "{=Dramalord208}{ACTOR1.LINK} and {ACTOR2.LINK} are not {TEXT1} anymore.";
        public const string LOG_BIRTH = "{=Dramalord211}{ACTOR3.LINK} was born to {ACTOR1.LINK} and {ACTOR2.LINK}.";
        public const string LOG_BIRTH_DEATH = "{=Dramalord212}The child of {ACTOR1.LINK} and {ACTOR2.LINK} died at birth.";
        public const string LOG_SEX_PRISON = "{=Dramalord251}{ACTOR1.LINK} released their captive {ACTOR2.LINK} in exchange for their 'special services'...";
        public const string LOG_MARRIAGE = "{=Dramalord265}{ACTOR1.LINK} married {ACTOR2.LINK}.";
        public const string LOG_LEAVE_CLAN = "{=Dramalord270}{ACTOR1.LINK} has left {TEXT1}.";
        public const string LOG_JOIN_CLAN = "{=Dramalord271}{ACTOR1.LINK} joined {TEXT1}.";
        public const string LOG_ORPHANIZE = "{=Dramalord348}{ACTOR1.LINK} put child {ACTOR2.LINK} into an orphanage.";
        public const string LOG_CONFRONTATION = "{=Dramalord349}{ACTOR1.LINK} learned {ACTOR2.LINK} is cheating on them.";
        public const string LOG_GOSSIP = "{=Dramalord360}{ACTOR1.LINK} shared gossip with {ACTOR2.LINK} about {ACTOR3.LINK} and {ACTOR4.LINK}.";
        public const string LOG_ADOPT = "{=Dramalord379}{ACTOR1.LINK} adopted orphan {ACTOR2.LINK}.";
        public const string LOG_ADOPT_2 = "{=Dramalord420}{ACTOR1.LINK} and {ACTOR3.LINK} adopted orphan {ACTOR2.LINK}.";
        public const string LOG_DUEL_WON = "{=Dramalord425}{ACTOR1.LINK} won a duel against {ACTOR2.LINK}.";
        public const string LOG_DUEL_LOST = "{=Dramalord426}{ACTOR1.LINK} lost a duel against {ACTOR2.LINK}.";

        public const string INTENTION_GREETING_UNKNOWN = "{=Dramalord172}Excuse me, {ACTOR1.LINK}. I do not believe we have been introduced, but might I trouble you for a moment of your time?";
        public const string INTENTION_GREETING_KNOWN = "{=Dramalord173}{ACTOR1.LINK}, it is a pleasure to see you. May I humbly request a moment of your time?";
        public const string INTENTION_REACT_YES = "{=Dramalord176}Of course, {ACTOR1.LINK}. What is it you wish to discuss?";
        public const string INTENTION_REACT_NO_TIME = "{=Dramalord177}My apologies, {ACTOR1.LINK}, but I am short of time right now.";
        public const string INTENTION_REACT_NO_INTEREST = "{=Dramalord181}I am sorry {ACTOR1.LINK}, but I have no interest in that right now.";
        public const string INTENTION_REACT_STOP = "{=Dramalord161}Stop bothering me with your profanities! Be gone!";

        public const string INTENTION_TALK_1 = "{=Dramalord178}I am always eager to hear new stories. Tell me of your latest exploits while traveling in the realm.";
        public const string INTENTION_TALK_2 = "{=Dramalord179}There is a matter that has weighed upon my thoughts for some time. I would value hearing your opinion.";
        public const string INTENTION_TALK_REACT_OK = "{=Dramalord180}Very well. Let us speak, then, {ACTOR1.LINK}.";

        public const string INTENTION_FLIRT_1 = "{=Dramalord182}I must admit that I find you quite charming. It would be a shame to not grow better acquainted.";
        public const string INTENTION_FLIRT_2 = "{=Dramalord183}Would you care to walk with me? I should enjoy the company of one so striking.";
        public const string INTENTION_FLIRT_REACT_OK = "{=Dramalord184}You make quite the impression. But tell me, what else should I know of you?";

        public const string INTENTION_DATE_FIRST_1 = "{=Dramalord185}I must confess, I cannot stop thinking of you. I have strong feelings for you, {ACTOR1.LINK}, and would see our bond grow deeper. What say you?";
        public const string INTENTION_DATE_FIRST_2 = "{=Dramalord186}Your presence stirs my heart, {ACTOR1.LINK}. I should very much like to see you more often—just the two of us, away from prying eyes. What do you think, {ACTOR1.LINK}?";
        public const string INTENTION_DATE_LOVER_1 = "{=Dramalord187}Ah, {ACTOR1.LINK}, I have missed you dearly. Might we share some time together?";
        public const string INTENTION_DATE_LOVER_2 = "{=Dramalord188}I had been hoping to see you, {ACTOR1.LINK}. Shall we seek a quieter place for a more... private discussion?";
        public const string INTENTION_DATE_CHEATING_1 = "{=Dramalord189}It seems we are in luck, {ACTOR1.LINK}. {ACTOR2.LINK} is away and will not return soon. Will you join me?";
        public const string INTENTION_DATE_CHEATING_2 = "{=Dramalord190}At last, {ACTOR2.LINK} is gone, and we have some precious moments of privacy. Will you come to me, {ACTOR1.LINK}?";
        public const string INTENTION_DATE_FIRST_REACT_OK = "{=Dramalord191}Oh {ACTOR1.LINK}, I wish for the very same!";
        public const string INTENTION_DATE_REACT_OK = "{=Dramalord192}Sure, {ACTOR1.LINK}, I always enjoy your company.";

        public const string INTENTION_MARRY_1 = "{=Dramalord266}I love you dearly, {ACTOR1.LINK}. The time has come to take the next step in our journey together. Will you marry me?";
        public const string INTENTION_MARRY_2 = "{=Dramalord267}You have my heart, {ACTOR1.LINK}, and I know that no other shall ever take your place. Will you do me the honor of marriage?";
        public const string INTENTION_MARRY_REACT_OK = "{=Dramalord268}You bring my dreams to life, {ACTOR1.LINK}. Yes, I would love to marry you!";
        public const string INTENTION_MARRY_REACT_NOW = "{=Dramalord390}We are in agreement, {ACTOR1.LINK}. Let us seal our bond together.";
        public const string INTENTION_MARRY_ENGAGE_ASK = "{=Dramalord301}{ACTOR1.LINK}, I humbly seek your blessing to take the hand of {ACTOR2.LINK} in marriage.";
        public const string INTENTION_MARRY_ENGAGE_OK = "{=Dramalord302}You have shown yourself to be honorable and true, and I see the love {ACTOR1.LINK} holds for you in her eyes. With that, I give my blessing. May your marriage be strong, your days joyful, and your hearts ever steadfast.";
        public const string INTENTION_MARRY_ENGAGE_NO = "{=Dramalord303}You? Marry {ACTOR1.LINK}? A lowly wretch with little to offer? {ACTOR1.LINK} is to wed someone of standing, not some starry-eyed fool who thinks love alone will keep a household.";

        public const string INTENTION_SEX_PRISON_1 = "{=Dramalord252}Prisoner, I would have a word with you.";
        public const string INTENTION_SEX_PRISON_2 = "{=Dramalord253}I might be persuaded to release you from your bonds. In exchange for 'services' in my bedroom.";
        public const string INTENTION_SEX_PRISON_REACT_OK = "{=Dramalord254}Truly? Well, I suppose I have little choice but to agree to your terms.";
        public const string INTENTION_SEX_PRISON_REACT_NO = "{=Dramalord255}How dare you attempt to stain my honor with such a proposition!";

        public const string INTENTION_BLACKMAIL_BETROTHED = "{=Dramalord213}I happened to pass by when you asked {ACTOR1.LINK} for their hand. If you do not want {ACTOR2.LINK} to learn about this, it will cost you {TEXT1}{GOLD_ICON}.";
        public const string INTENTION_BLACKMAIL_DATE = "{=Dramalord214}It is nice to see that you and {ACTOR1.LINK} are sweethearts. For {TEXT1}{GOLD_ICON} {ACTOR2.LINK} will never learn what happened.";
        public const string INTENTION_BLACKMAIL_SEX = "{=Dramalord215}You and {ACTOR1.LINK} were moaning so loudly that almost everyone could hear it. I wonder what {ACTOR2.LINK} would say to that? {TEXT1}{GOLD_ICON} would silence that noise.";
        public const string INTENTION_BLACKMAIL_DAYS = "{=Dramalord216}I will give you {TEXT1} days to get the coins. See you soon, {ACTOR1.LINK}!";

        public const string INTENTION_VISIT_1_INTIME = "{=Dramalord260}Oh, {ACTOR1.LINK}, you have finally come! I was desperately awaiting your arrival!";
        public const string INTENTION_VISIT_1_LATE = "{=Dramalord261}Ah, look who it is. You have finally decided that I am worthy of your time then, {ACTOR1.LINK}?";
        public const string INTENTION_VISIT_2_INTIME = "{=Dramalord263}Oh, I fear the matter is most dire indeed! Cast aside your garments, {ACTOR1.LINK}, and follow me at once. Your expertise is required in a most delicate affair!";
        public const string INTENTION_VISIT_2_LATE = "{=Dramalord264}Alas, {ACTOR1.LINK}, you have tarried too long. Another has already seen to my... predicament. Your services are no longer required. Farewell.";
        public const string INTENTION_VISIT_REACT_1 = "{=Dramalord262}Here I am. What is this issue of urgency that requires my attention?";

        public const string INTENTION_PRISON = "{=Dramalord380}{ACTOR1.LINK}, let us talk about your future.";
        public const string INTENTION_PRISON_OK = "{=Dramalord381}It is not as if I have much of a choice, is it {ACTOR1.LINK}.";
        public const string INTENTION_PRISON_NO = "{=Dramalord382}I have no interest in conversing with the likes of you. Begone!";
        public const string INTENTION_PRISON_OFFER = "{=Dramalord383}I might be persuaded to release you from your bonds. In exchange for 'services' in my bedroom.";
        public const string INTENTION_PRISON_KILL = "{=Dramalord384}It is time to end this. Your existence is a nuisance.";
        public const string INTENTION_PRISON_OFFER_OK = "{=Dramalord385}Truly? Well, I suppose I have little choice but to agree to your terms. I may as well at least try to enjoy it...";
        public const string INTENTION_PRISON_OFFER_NO = "{=Dramalord386}How dare you attempt to stain my honor with such a proposition! You disgust me! I would never.";
        public const string INTENTION_PRISON_KILL_OK = "{=Dramalord387}Do what you must then, you vile and honorless swine!";

        public const string INTENTION_DIVORCE_DRAW_WEAPON = "{=Dramalord427}Draw you weapon and let us settle this matter once and for all.";
        public const string INTENTION_DIVORCE_START = "{=Dramalord428}{ACTOR1.LINK} I need to talk to you about {ACTOR2.LINK}";
        public const string INTENTION_DIVORCE_START_NO = "{=Dramalord429}Visit me in a settlement if you have the urge to talk about personal matters.";
        public const string INTENTION_DIVORCE_START_OK = "{=Dramalord430}Very well. What do you have to say?";
        public const string INTENTION_DIVORCE_REQUEST = "{=Dramalord431}I want you to end this farce of a marriage and set {ACTOR1.LINK} free.";
        public const string INTENTION_DIVORCE_REQUEST_PAY = "{=Dramalord432}I do not care much about {ACTOR1.LINK}. If you compensate my financial loss I am glad to anul this marriage.";
        public const string INTENTION_DIVORCE_REQUEST_FIGHT = "{=Dramalord433}If you want to break my love to {ACTOR1.LINK} you will have to stab my heart. Good luck trying.";
        public const string INTENTION_DIVORCE_PAY = "{=Dramalord434}Agreed. Here are {TEXT1}{GOLD_ICON} compensation.";

        public const string CONFRONTATION_GREETING_UNKNOWN = "{=Dramalord195}Greetings, {ACTOR1.LINK}, you do not yet know me. I am {ACTOR2.LINK} of the {TEXT1}.";
        public const string CONFRONTATION_GREETING_KNOWN = "{=Dramalord196}Good day, {ACTOR1.LINK}. It is fortunate that I have caught you.";

        public const string CONFRONTATION_DATE_OTHER = "{=Dramalord197}It seems that you and {ACTOR1.LINK} were...enjoying yourselves. Are you aware that they are {TEXT1}?";
        public const string CONFRONTATION_DATE_PLAYER = "{=Dramalord198}It is apparent that you and {ACTOR1.LINK} often conduct 'private meetings'. Have you forgotten that you are {TEXT1}?";
        public const string CONFRONTATION_SEX_OTHER = "{=Dramalord350}Huh...so you and {ACTOR1.LINK} were enjoying each other's company...in bed. You do know that they are {STATUS}, right?";
        public const string CONFRONTATION_SEX_PLAYER = "{=Dramalord351}So, {ACTOR1.LINK} has been keeping you entertained in bed? You are {TEXT1}, or has that slipped your mind?";
        public const string CONFRONTATION_BIRTH_OTHER = "{=Dramalord353}{ACTOR2.LINK} has given birth to {ACTOR1.LINK}, and it seems you are the father. I thought you were {TEXT1}?";
        public const string CONFRONTATION_BIRTH_PLAYER = "{=Dramalord352}So you have given birth to {ACTOR1.LINK}. It is no secret that the child's true father is {ACTOR2.LINK}, and not myself. Yet you are {TEXT1}, are you not?";
        public const string CONFRONTATION_MARRIAGE_OTHER = "{=Dramalord354}I have heard that you wed {ACTOR1.LINK}. I assume they have neglected to inform you that they are, in fact, {TEXT1}?";
        public const string CONFRONTATION_MARRIAGE_PLAYER = "{=Dramalord355}You wed {ACTOR1.LINK} behind my back. Did it never occur to you to inform me? You are {TEXT1}!";

        public const string CONFRONTATION_RESULT_OK = "{=Dramalord199}I forgive you, {ACTOR1.LINK}. But mark my words — I shall not forget this.";
        public const string CONFRONTATION_RESULT_BREAKUP = "{=Dramalord200}I cannot accept this, {ACTOR1.LINK}. You are undeserving of anything more from me. Our relationship ends here.";
        public const string CONFRONTATION_RESULT_NO_RELATION = "{=Dramalord201}This will not be forgotten, {ACTOR1.LINK}. Farewell.";
        public const string CONFRONTATION_RESULT_LEAVE = "{=Dramalord202}I do not know what to say. This has left me utterly distraught. I need some time to consider things.";
        public const string CONFRONTATION_RESULT_BREAKUP_OTHER = "{=Dramalord407}You will end this... 'thing' with {ACTOR1.LINK} and you will not see them again!";

        public const string GOSSIP_MARRIAGE = "{=Dramalord356}Did you hear? {ACTOR1.LINK} and {ACTOR2.LINK} are now husband and wife — though with all that has been said, one wonders if vows alone will silence the rumors.";
        public const string GOSSIP_DATE = "{=Dramalord357}Word travels fast — {ACTOR1.LINK} and {ACTOR2.LINK} have been meeting in secret, though if they wish to remain unnoticed, they should be less obvious with their stolen glances.";
        public const string GOSSIP_SEX = "{=Dramalord358}Well, the whole castle is aflutter! {ACTOR1.LINK} and {ACTOR2.LINK} were found abed together, and not even the dawn could wash away the scandal.";
        public const string GOSSIP_BIRTH = "{=Dramalord359}Whispers abound — {ACTOR1.LINK} and {ACTOR2.LINK} have welcomed a child, though some say the timing is rather... convenient.";

        public const string PLAYER_INTERACTION_START = "{=Dramalord272}{ACTOR1.LINK}, may I occupy a few minutes of your time?";
        public const string PLAYER_INTERACTION_END = "{=Dramalord273}Let us talk about something else, {ACTOR1.LINK}.";
        public const string PLAYER_INTERACTION_TALK = "{=Dramalord276}It may do us well to share our thoughts. Care to talk? (Friendly chat)";
        public const string PLAYER_INTERACTION_FLIRT = "{=Dramalord277}You look stunning, {ACTOR1.LINK}, though I suspect you are already well aware... (Flirting)";
        public const string PLAYER_INTERACTION_DATING_START = "{=Dramalord278}I must confess I have feelings for you, {ACTOR1.LINK}! (Love affair)";
        public const string PLAYER_INTERACTION_DATING = "{=Dramalord279}There is nothing I desire more than to be with you, and you alone. (Dating)";
        public const string PLAYER_INTERACTION_SEX = "{=Dramalord280}I crave your touch, {ACTOR1.LINK}. Will you grant me this indulgence? (Intimacy)";
        public const string PLAYER_INTERACTION_MARRIAGE_START = "{=Dramalord281}I love you dearly, {ACTOR1.LINK}. There is no road that I wish to walk without you. Will you marry me? (Propose)";
        public const string PLAYER_INTERACTION_MARRIAGE = "{=Dramalord282}Now that we are in a settlement, {ACTOR1.LINK}, let us seek an officiant and finally be wed! (Marriage)";
        public const string PLAYER_INTERACTION_BREAK_UP = "{=Dramalord283}This is not working, {ACTOR1.LINK}. Let us put an end to this charade before it turns to bitterness. (Break up)";
        public const string PLAYER_INTERACTION_DIVORCE_SPOUSE = "{=Dramalord294}My love, {ACTOR1.LINK} is an obstacel for our relationship. (Divorce spouse)";
        public const string PLAYER_INTERACTION_ASK_INFO = "{=Dramalord318}{ACTOR1.LINK}, I am curious — might you share what qualities you favor in a partner? (Information)";
        public const string PLAYER_INTERACTION_APPROACH = "{=Dramalord396}You may approach me again if you want to talk to me, {ACTOR1.LINK}.";
        public const string PLAYER_INTERACTION_GOSSIP = "{=Dramalord408}Heard any noteworthy news of late?";
        public const string PLAYER_INTERACTION_GOSSIP_MORE = "{=Dramalord410}Aynthing else?";

        public const string PLAYER_CONFRONT_NPC_INTRO = "{=Dramalord399}Oh, hello {ACTOR1.LINK}. I... didn't expect you...";
        public const string PLAYER_CONFRONT_ACCUSE = "{=Dramalord406}So you and {ACTOR1.LINK}, eh? Did you think I wouldn't notice?";
        public const string PLAYER_CONFRONT_NPC_PLAYING_INNOCENT = "{=Dramalord405}But {ACTOR1.LINK}... this is all just a misunderstanding! I.. I...";

        public const string NPC_INTERACTION_ASYOUWISH = "{=Dramalord284}As you wish, {ACTOR1.LINK}.";
        public const string NPC_INTERACTION_UHWELL = "{=Dramalord291}Uh... well...";
        public const string NPC_INTERACTION_SPOUSE_NEARBY = "{=Dramalord292}Apologies, {ACTOR1.LINK}, but my spouse is around. Let us talk about that some other time.";
        public const string NPC_INTERACTION_TIMEOUT = "{=Dramalord285}Again? Give me some rest, {ACTOR1.LINK}. Let us talk about it later.";
        public const string NPC_INTERACTION_TALK_1 = "{=Dramalord286}Certainly! I am game for a good conversation.";
        public const string NPC_INTERACTION_FLIRT_1 = "{=Dramalord287}Ah, you are bold, {ACTOR1.LINK}. I wonder, is your wit as sharp as your tongue? Let us find out.";
        public const string NPC_INTERACTION_DATE_FIRST_1 = "{=Dramalord288}You know, {ACTOR1.LINK}... I have dreamt of this moment since I first laid eyes on you.";
        public const string NPC_INTERACTION_DATE_1 = "{=Dramalord289}Of course, {ACTOR1.LINK}. Let us spend some time together, just the two of us.";
        public const string NPC_INTERACTION_DATE_CHEATING_OK = "{=Dramalord290}It seems we are in luck, {ACTOR1.LINK}. {ACTOR2.LINK} is away and will not return soon. Will you join me?";
        public const string NPC_INTERACTION_SEX_OK = "{=Dramalord293}Set aside your garments, and I shall show you a different kind of battle—one fought in my bedchamber, where both sides emerge victorious.";
        public const string NPC_INTERACTION_MARRIAGE_OK = "{=Dramalord296}You bring my dreams to life, {ACTOR1.LINK}. Yes, I would love to marry you!";
        public const string NPC_INTERACTION_ENGAGE_OK = "{=Dramalord297}If you truly wish to make me yours, then you must seek the blessing of {ACTOR1.LINK}. My heart is already yours, but it is their permission that will grant us the future we both desire.";
        public const string NPC_INTERACTION_ENGAGE_NO = "{=Dramalord298}I am sorry, {ACTOR1.LINK}, but I am not ready for that step just yet.";
        public const string NPC_INTERACTION_BREAKUP_OK = "{=Dramalord306}Oh no, {ACTOR1.LINK}! My heart breaks, yet I know I have no choice but to accept your decision...";
        public const string NPC_INTERACTION_GOSSIP_NONE = "{=Dramalord409}Nothing comes to mind at the moment.";
        public const string NPC_INTERACTION_DIVORCE_OK = "{=Dramalord411}You are right, {ACTOR1.LINK}. I have no feelings for {ACTOR2.LINK} anymore. Can you talk to them and make sure they won't bother us anymore?";
        public const string NPC_INTERACTION_DIVORCE_NO = "{=Dramalord412}I am sorry, {ACTOR1.LINK} but I have still feelings for {ACTOR2.LINK}. For the time being I will stay in this marriage.";

        public const string NPC_INTERACTION_INFO_OK = "{=Dramalord309}Certainly, {ACTOR1.LINK}. If you truly wish to know, I shall tell you...";
        public const string NPC_INTERACTION_INFO_NO = "{=Dramalord308}Forgive me, {ACTOR1.LINK}, but I do not trust you well enough to discuss this with you.";
        public const string NPC_INTERACTION_INFO_HETERO = "{=Dramalord310}I find myself primarily drawn to those of the opposite sex. As the saying goes, opposites attract.";
        public const string NPC_INTERACTION_INFO_HOMO = "{=Dramalord311}I am most inclined toward those of my own sex. As they say, birds of a feather flock together.";
        public const string NPC_INTERACTION_INFO_BI = "{=Dramalord312}I am captivated by both men and women alike, for I see beauty in both.";
        public const string NPC_INTERACTION_INFO_ASEX = "{=Dramalord313}I do not feel particularly drawn to either sex, truthfully.";
        public const string NPC_INTERACTION_INFO_WEIGHT_LOW = "{=Dramalord314}I find that slender figures possess a certain elegance.";
        public const string NPC_INTERACTION_INFO_WEIGHT_MID = "{=Dramalord315}I prefer a balance — not too thin, nor too large. A form that is just right.";
        public const string NPC_INTERACTION_INFO_WEIGHT_HIGH = "{=Dramalord316}I favor those of a fuller figure—more to hold, more to enjoy.";
        public const string NPC_INTERACTION_INFO_BUILD_LOW = "{=Dramalord317}I tend towards those who are lean. Sometimes less is more.";
        public const string NPC_INTERACTION_INFO_BUILD_MID = "{=Dramalord318}A well-toned body suits me best. Althletic, maybe, but nothing excessive. Somewhere in the middle.";
        public const string NPC_INTERACTION_INFO_BUILD_HIGH = "{=Dramalord319}I am quite fond of strong, muscular figures. The more imposing, the better.";
        public const string NPC_INTERACTION_INFO_AGE_DIFF = "{=Dramalord320}I am drawn to those who are {TEXT1} than myself. I prefer partners around the age of {TEXT2}.";
        public const string NPC_INTERACTION_INFO_RESULT = "{=Dramalord321}As for you {ACTOR1.LINK}, I think you are probably a... {TEXT1} out of 100.";

        public const string ORPHANAGE_ADOPT = "{=Dramalord361}I would like to extend my family and adopt an orphan.";
        public const string ORPHANAGE_ORPHANIZE = "{=Dramalord362}I want to be rid of a child in my clan.";
        public const string ORPHANAGE_ADOPT_BOY_GIRL = "{=Dramalord363}Oh, that is great {ACTOR1.LINK}! We have currently {TEXT1} boys and {TEXT2} girls in our orphanage.";
        public const string ORPHANAGE_ADOPT_EMPTY = "{=Dramalord364}My apologies {ACTOR1.LINK}, but there are currently no children in our orphanage.";
        public const string ORPHANAGE_ADOPT_BOY = "{=Dramalord365}I would like to adopt a boy.";
        public const string ORPHANAGE_ADOPT_GIRL = "{=Dramalord366}I would like to adopt a girl.";
        public const string ORPHANAGE_ADOPT_WHO = "{=Dramalord367}Who would you like to adopt?";
        public const string ORPHANAGE_ADOPT_SELECT = "{=Dramalord368}{ACTOR1.LINK}, {TEXT1} years old.";
        public const string ORPHANAGE_ADOPT_OTHER = "{=Dramalord369}I am thinking of a different child.";
        public const string ORPHANAGE_ADOPT_CONFIRM = "{=Dramalord370}Very well. Are you absolutely sure you want to adopt {ACTOR1.LINK}?";
        public const string ORPHANAGE_ADOPT_FINISHED = "{=Dramalord371}Congratulations! I am sure {ACTOR1.LINK} will be in good hands.";
        public const string ORPHANAGE_ADOPT_ABORT = "{=Dramalord372}Oh well, that's sad. {ACTOR1.LINK} will be very disappointed.";
        public const string ORPHANAGE_ORPHANIZE_OK = "{=Dramalord373}Of course {ACTOR1.LINK}, we can arrange that.";
        public const string ORPHANAGE_ORPHANIZE_EMPTY = "{=Dramalord374}{ACTOR1.LINK}, it appears that there are no children in your clan.";
        public const string ORPHANAGE_ORPHANIZE_WHO = "{=Dramalord375}Who would be the unfortunate child that we should take into our custody?";
        public const string ORPHANAGE_ORPHANIZE_CONFIRM = "{=Dramalord376}Very well. Are you absolutely sure you want to give away {ACTOR1.LINK}?";
        public const string ORPHANAGE_ORPHANIZE_FINISHED = "{=Dramalord377}Then it is decided. We will take care of {ACTOR1.LINK} and find a new home for the child. Please bid your farewells and leave their belongings with us.";
        public const string ORPHANAGE_ORPHANIZE_ABORT = "{=Dramalord378}Very well, {ACTOR1.LINK}. {ACTOR2.LINK} will stay in your clan.";

        public const string BACKSTORY_START = "{=Dramalord149}My childhood was not easy. I grew up an urchin on the streets, cared for by the local gang.";
        public const string BACKSTORY_GENERAL = "{=Dramalord150}The leader fed us scarcely and would send us off to rob and steal. If we we could not bring home enough spoils by end of day, we were beaten.";
        public const string BACKSTORY_FEMALE_1 = "{=Dramalord151}As soon as I grew teats I was sent to the tavern. I had to entertain disgusting men and make them spend their money on drinks.. or on me.";
        public const string BACKSTORY_FEMALE_2 = "{=Dramalord152}Once there was an old, orange faced guy who constantly grabbed me by the... you know... without paying. So I kicked him in the nuts and fled out of the town.";
        public const string BACKSTORY_FEMALE_3 = "{=Dramalord153}Anyway, I figured that it was better to stab than be 'stabbed', so to speak. So, I made it my new business.";
        public const string BACKSTORY_MALE_1 = "{=Dramalord154}As soon as I had a single hair upon my chest I was sent off to the castles as a servant for elderly ladies. I would 'entertain' them while their husbands were off at war.";
        public const string BACKSTORY_MALE_2 = "{=Dramalord155}One night, while 'planting seeds' in the 'old silver forest', the heart of the, uh, forest's owner seemed to simply stop. I panicked, thinking that I would be found to blame. So I fled.";
        public const string BACKSTORY_MALE_3 = "{=Dramalord156}So, the times working with my wood are over, switched to sword and axe instead. Turns out I'm quite good with that too.";
        public const string BACKSTORY_FEMALE_2_REPLY_1 = "{=Dramalord157}Lord Stickyfinger did not deserve any better I suppose.";
        public const string BACKSTORY_FEMALE_2_REPLY_2 = "{=Dramalord158}Ouch! That's quite the punishment.";
        public const string BACKSTORY_MALE_2_REPLY_1 = "{=Dramalord159}It must have been hard being a young buck in old forests.";
        public const string BACKSTORY_MALE_2_REPLY_2 = "{=Dramalord160}Well, young timber hardly belongs in ancient forests, does it?";

        public const string PERSUASION_DATE_Q = "{=Dramalord327}I feel uncertain about this. I do care for you, but is it enough?";
        public const string PERSUASION_DATE_1 = "{=Dramalord328}If we never try, we will never know what might have been.";
        public const string PERSUASION_DATE_2 = "{=Dramalord329}You are overthinking this. Trust your heart.";
        public const string PERSUASION_DATE_3 = "{=Dramalord330}I truly believe that we could build something lasting, if we choose to.";
        public const string PERSUASION_DATE_4 = "{=Dramalord331}I would be honored if you would have me.";
        public const string PERSUASION_MARRIAGE_Q = "{=Dramalord332}This is all so overwhelming... I love you, {PLAYER.NAME}, but are we truly ready?";
        public const string PERSUASION_MARRIAGE_1 = "{=Dramalord333}Love is a journey, and I would see where this road leads us.";
        public const string PERSUASION_MARRIAGE_2 = "{=Dramalord334}This feels right. There is nowhere else for us to go but forward.";
        public const string PERSUASION_MARRIAGE_3 = "{=Dramalord335}At last, we could share everything with each other.";
        public const string PERSUASION_MARRIAGE_4 = "{=Dramalord336}In truth, this is the only honorable course before us.";
        public const string PERSUASION_SEX_Q = "{=Dramalord337}This is quite the scandalous suggestion... What if er are caught?";
        public const string PERSUASION_SEX_1 = "{=Dramalord338}What is passion without a little risk?";
        public const string PERSUASION_SEX_2 = "{=Dramalord339}Then we shall face whatever comes, together.";
        public const string PERSUASION_SEX_3 = "{=Dramalord340}Just imagine the pleasure we could share...";
        public const string PERSUASION_SEX_4 = "{=Dramalord341}Then we release each other and return to what was before.";

        public const string QUESTION_POI = "{=Dramalord088}Tell me, {ACTOR1.LINK}, as you travel wide and meet many, do you have an opinion of {ACTOR2.LINK}?";
        public const string QUESTION_POI_MET_LIKE = "{=Dramalord089}Ah, {ACTOR1.LINK}! Yes, we have met. I am actually quite fond of them.";
        public const string QUESTION_POI_MET_DISLIKE = "{=Dramalord090}Unfortunately, yes. I have met {ACTOR1.LINK} and do not regard them kindly.";
        public const string QUESTION_POI_MET_NOCARE = "{=Dramalord091}{ACTOR1.LINK}, you say? I harbor no feelings for them one way or the other.";
        public const string QUESTION_POI_NOTMET_LIKE = "{=Dramalord092}Oh, {ACTOR1.LINK}? We have yet to meet, but I hope to, and have heard good things.";
        public const string QUESTION_POI_NOTMET_DISLIKE = "{=Dramalord093}From what I have heard, I have been spared a misfortune in not having met {ACTOR1.LINK}.";
        public const string QUESTION_POI_NOTMET_NOCARE = "{=Dramalord094}I hold no opinion of {ACTOR1.LINK}, as we have yet to exchange words.";
        public const string QUESTION_POI_LIKE_SUCCESS = "{=Dramalord095}That is good to hear! {ACTOR1.LINK} is a fine person to know.";
        public const string QUESTION_POI_LIKE_FAIL = "{=Dramalord096}That is most unfortunate. {ACTOR1.LINK} and I get along quite well.";
        public const string QUESTION_POI_LIKE_NOCARE = "{=Dramalord097}Oh? That is a pity. {ACTOR1.LINK} is someone I have always thought well of.";
        public const string QUESTION_POI_DISLIKE_FAIL = "{=Dramalord098}Hmph. You admire {ACTOR1.LINK}? How very disappointing.";
        public const string QUESTION_POI_DISLIKE_SUCCESS = "{=Dramalord099}I completely agree! {ACTOR1.LINK} left a very poor impression on me.";
        public const string QUESTION_POI_DISLIKE_NOCARE = "{=Dramalord100}Well, I do not care for {ACTOR1.LINK} much at all.";
        public const string QUESTION_POI_NOCARE_FAIL = "{=Dramalord101}You seem quick to form an opinion about {ACTOR1.LINK}, I have to say.";
        public const string QUESTION_POI_NOCARE_SUCCESS = "{=Dramalord102}I do not harbor an opinion about {ACTOR1.LINK}, either. I do not yet know them well enough.";

        public const string QUESTION_TRAIT_AGREE = "{=Dramalord103}That is an excellent point of view! Agreed.";
        public const string QUESTION_TRAIT_DISAGREE = "{=Dramalord104}Well, I am afraid I must disagree with you on that.";
        public const string QUESTION_TRAIT_NOCARE = "{=Dramalord105}Hm. You seem to be quite opinionated.";
        public const string QUESTION_TRAIT_HONOR = "{=Dramalord106}I heard tale of a warrior that was executed for renouncing his oaths and turning to banditry, but it is said that he did it to feed the hungry. Did his ends justify his means? What do you think? (Honor)";
        public const string QUESTION_TRAIT_HONOR_GOOD = "{=Dramalord107}There is always another way, even if it presents great difficulty. One should not compromise their honor.";
        public const string QUESTION_TRAIT_HONOR_BAD = "{=Dramalord108}Having a code is almost as important as knowing when to break it.";
        public const string QUESTION_TRAIT_HONOR_NOCARE = "{=Dramalord109}People starve, people steal, and people die. It is just the way of things.";
        public const string QUESTION_TRAIT_VALOR = "{=Dramalord110}I recently heard a story about a great commander who won a difficult victory against impossible odds. Would you still go to battle if you knew the odds were against you? (Valor)";
        public const string QUESTION_TRAIT_VALOR_GOOD = "{=Dramalord111}Yes, I would. Sometimes it is more important to fight than to be victorious. The world belongs to the brave.";
        public const string QUESTION_TRAIT_VALOR_BAD = "{=Dramalord112}No. Why would I risk my life when I am certain to lose? That would be foolish.";
        public const string QUESTION_TRAIT_VALOR_NOCARE = "{=Dramalord113}Hm. I cannot say. I think that it would depend on the situation.";
        public const string QUESTION_TRAIT_MERCY = "{=Dramalord114}I have heard that some lords allow defeated foes to leave the battlefield unharmed. Some think it admirable, others deem it a dangerous folly. What do you think? (Mercy)";
        public const string QUESTION_TRAIT_MERCY_GOOD = "{=Dramalord115}They allowed them to go home to their families. I would do the same.";
        public const string QUESTION_TRAIT_MERCY_BAD = "{=Dramalord116}Off with their heads, I say! That would make it difficult for them to march to battle again.";
        public const string QUESTION_TRAIT_MERCY_NOCARE = "{=Dramalord117}It is the nature of war—some live, some do not. That is just the way of things.?";
        public const string QUESTION_TRAIT_GENEROSITY = "{=Dramalord118}Recently, I heard tale told of an arena champion who gave all of his tournament winnings away to the poor. (Generosity)";
        public const string QUESTION_TRAIT_GENEROSITY_GOOD = "{=Dramalord119}That is quite the act of generosity. People such as that are a rarity, unfortunately.";
        public const string QUESTION_TRAIT_GENEROSITY_BAD = "{=Dramalord120}Bah! What a waste. What is the point of gold and glory if not to keep it?";
        public const string QUESTION_TRAIT_GENEROSITY_NOCARE = "{=Dramalord121}Well, I suppose that it is their money, thus it is their choice.";
        public const string QUESTION_TRAIT_CALCULATING = "{=Dramalord122}I heard that a noble clan nearly turned against their own king after being denied a request. Some call it reckless, others see it as a bold gambit. What do you think? (Calculating)";
        public const string QUESTION_TRAIT_CALCULATING_GOOD = "{=Dramalord123}That was a rash decision. One should not throw away power over a fleeting insult.";
        public const string QUESTION_TRAIT_CALCULATING_BAD = "{=Dramalord124}I can understand the urge. Sometimes you must act on your convictions, consequences be damned.";
        public const string QUESTION_TRAIT_CALCULATING_NOCARE = "{=Dramalord125}Difficult to say. Life is complicated, and I can hardly judge such things.";

        public const string QUESTION_PHYSICAL_GOOD = "{=Dramalord126}Oh, you are making me blush! I am delighted to hear that.";
        public const string QUESTION_PHYSICAL_BAD = "{=Dramalord127}Does that mean you do not consider me to be attractive?";
        public const string QUESTION_PHYSICAL_NOCARE = "{=Dramalord128}You truly do not have any preference? Hm.";
        public const string QUESTION_PHYSICAL_ORIENTATION = "{=Dramalord129}Do you prefer the company of those alike to yourself, or do you find charm in a more opposite sort? (Orientation)";
        public const string QUESTION_PHYSICAL_WEIGHT = "{=Dramalord130}I overheard a debate at the tavern—some were saying they enjoy a fuller figure, while others prefer a leaner form. What do you think? (Weight)";
        public const string QUESTION_PHYSICAL_BUILD = "{=Dramalord131}Many people admire a strong and powerful form. Others like the slender and agile. Where do your tastes lie? (Build)";
        public const string QUESTION_PHYSICAL_AGE = "{=Dramalord132}Some are known to rob the cradle, others are known to rob the grave. What about you? (Age)";
        public const string QUESTION_PHYSICAL_AGE_OLDER = "{=Dramalord133}I tend towards people older than myself. They say that wine grows better with age.";
        public const string QUESTION_PHYSICAL_AGE_YOUNGER = "{=Dramalord134}I enjoy the company of people younger than myself. I find their energy invigorating.";
        public const string QUESTION_PHYSICAL_AGE_SAME = "{=Dramalord135}I usually enjoy being around people near to my own age.";

        public const string QUESTION_PERSONALITY_JEALOUSY = "{=Dramalord136}If an admirer of yours keeps on flirting with other people - does this make you angry? (Jealousy)";
        public const string QUESTION_PERSONALITY_JEALOUSY_GOOD = "{=Dramalord137}Of course it does! They should only have eyes for me and no one else!";
        public const string QUESTION_PERSONALITY_JEALOUSY_BAD = "{=Dramalord138}Not at all, let them have some fun I say. No one is hurt by that.";
        public const string QUESTION_PERSONALITY_JEALOUSY_NOCARE = "{=Dramalord139}Well, I guess that depends on the situation...";
        public const string QUESTION_PERSONALITY_SOCIABILITY = "{=Dramalord140}Feasts bring together all sorts—lords, merchants, poets, and travelers. Some relish the company, while others prefer a quiet corner. What about you? (Sociability)";
        public const string QUESTION_PERSONALITY_SOCIABILITY_GOOD = "{=Dramalord141}Oh, absolutely! I thrive in good company. The more people, the better!";
        public const string QUESTION_PERSONALITY_SOCIABILITY_BAD = "{=Dramalord142}I prefer to keep to myself. Large crowds can be exhausting.";
        public const string QUESTION_PERSONALITY_SOCIABILITY_NOCARE = "{=Dramalord143}Well, I suppose that depends. I enjoy company, but too much can be overwhelming.";
        public const string QUESTION_PERSONALITY_EMPATHY = "{=Dramalord144}When a friend confides in you about something that weighs heavily on their heart. Do you offer comfort, or is it best they handle it on their own? (Empathy)";
        public const string QUESTION_PERSONALITY_EMPATHY_GOOD = "{=Dramalord145}Of course, I try to comfort them. If I can help, I will.";
        public const string QUESTION_PERSONALITY_EMPATHY_BAD = "{=Dramalord146}Truthfully, I am not always the best person for that. People must learn to handle their own troubles.";
        public const string QUESTION_PERSONALITY_EMPATHY_NOCARE = "{=Dramalord147}I suppose that it depends on my mood and the situation.";
        public const string QUESTION_END = "{=Dramalord148}Thank you for the conversation, {ACTOR1.LINK}.";

        public const string QUEST_BLACKMAIL_TITLE = "{=Dramalord217}{ACTOR1.NAME} is blackmailing you.";
        public const string QUEST_BLACKMAIL_INFO = "{=Dramalord218}{ACTOR1.LINK} saw you and {ACTOR2.LINK}. They threaten you to tell {ACTOR3.LINK} if you do not pay them {TEXT1}{GOLD_ICON}. Visit them during night time and resolve that matter, or pay what they want.";
        public const string QUEST_BLACKMAIL_PAID = "{=Dramalord219}You have paid {ACTOR1.LINK} {TEXT1}{GOLD_ICON}.";
        public const string QUEST_BLACKMAIL_BEATEN = "{=Dramalord220}You showed {ACTOR1.LINK} what happens if they mess with you.";
        public const string QUEST_BLACKMAIL_KILLED = "{=Dramalord221}You silenced {ACTOR1.LINK} forever.";
        public const string QUEST_VISIT_TITLE = "{=Dramalord258}{ACTOR1.NAME} requests your presence.";
        public const string QUEST_VISIT_INFO = "{=Dramalord257}{ACTOR1.LINK} seeks your presence regarding a matter of great urgency. Will you arrive in time?";
        public const string QUEST_VISIT_SUCCESS = "{=Dramalord259}{ACTOR1.LINK} is pleased that you have seen their request through to completion...";
        public const string QUEST_VISIT_FAILED = "{=Dramalord256}{ACTOR1.LINK} is disappointed in you, for you have failed to fulfill their urgent request...";
        public const string QUEST_MARRIAGE_TITLE = "{=Dramalord299}Ask {ACTOR1.NAME} for their hand in marriage.";
        public const string QUEST_MARRIAGE_INFO = "{=Dramalord300}{ACTOR1.LINK} told you that you require the permission of {ACTOR2.LINK} in order to marry them.";
        public const string QUEST_MARRIAGE_BLESSING = "{=Dramalord304}{ACTOR1.LINK} gave you their blessing to marry {ACTOR2.LINK}. Bring them to a settlement to seal your bond.";
        public const string QUEST_MARRIAGE_FAILED = "{=Dramalord305}You failed to get the blessing of {ACTOR1.LINK} and marry {ACTOR2.LINK} on time.";
        public const string QUEST_CONFRONT_INFO = "{=Dramalord402}{ACTOR1.LINK} was cheating on you with {ACTOR2.LINK}. Confront them.";
        public const string QUEST_CONFRONT_SUCCESS = "{=Dramalord403}You confronted {ACTOR1.LINK}.";
        public const string QUEST_CONFRONT_FAILED = "{=Dramalord404}You failed to confront {ACTOR1.LINK} in time.";
        public const string QUEST_DIVORCE_TITLE = "{=Dramalord435}Convince {ACTOR2.NAME} to divorce {ACTOR1.NAME}.";
        public const string QUEST_DIVORCE_INFO = "{=Dramalord436}{ACTOR1.LINK} asked you to take care about their divorce from {ACTOR2.LINK}."; 

        public const string INQUIRY_SEX_TITLE = "{=Dramalord193}Opportunity for intimacy";
        public const string INQUIRY_SEX_TEXT = "{=Dramalord194}There is a certain heat in {ACTOR1.LINK}'s gaze, their smile laced with unmistakable intent. Will you answer their invitation?";
        public const string INQUIRY_MARRIAGE_TITLE = "{=Dramalord393}Marriage Request";
        public const string INQUIRY_MARRIAGE_ALLOW = "{=Dramalord394}{ACTOR1.LINK} and {ACTOR2.LINK} would like to marry. As clan leader you have to agree to that bond. What is your answer?";
        public const string INQUIRY_MARRIAGE_JOIN_CLAN = "{=Dramalord393}Should {ACTOR1.LINK} join your clan after marriage?";
        public const string INQUIRY_MARRIAGE_JOIN_CLAN_2 = "{=Dramalord419}{ACTOR1.LINK} and {ACTOR2.LINK} newly wed. In which clan should they start their life together?";
        public const string INQUIRY_CONFRONT_TITLE = "{=Dramalord400}Cheater caught!";
        public const string INQUIRY_CONFRONT_TEXT = "{=Dramalord401}{ACTOR1.LINK} was cheating on you with {ACTOR2.LINK}! Do you want to confront them?";
        public const string INQUIRY_BASTARD_TITLE = "{=Dramalord417}Take your bastard?";
        public const string INQUIRY_BASTARD_TEXT = "{=Dramalord418}{ACTOR1.LINK} has given birth to your child. As you are not married, {ACTOR1.LINK} would be forced to give the child to an orphanage. Will you take care of the child instead?";
                     
        public const string BANNER_RELATION_CHANGE = "{=Dramalord203}Your relation to {ACTOR1.LINK} has changed. (Love {TEXT1}, Trust {TEXT2})";
        public const string BANNER_RELATIONSHIP_START = "{=Dramalord209}{ACTOR1.LINK} and you are now {TEXT1}.";
        public const string BANNER_RELATIONSHIP_END = "{=Dramalord210}{ACTOR1.LINK} and you are not {TEXT1} anymore.";
        public const string BANNER_INFO_LEARNED = "{=Dramalord307}You learned the physical preferences of {ACTOR1.LINK}.";
        public const string BANNER_INFO_PERSIUASION_SUCCESS = "{=Dramalord325}You successfully convinced {ACTOR1.LINK}.";
        public const string BANNER_INFO_PERSIUASION_FAIL = "{=Dramalord326}You failed to convince {ACTOR1.LINK}.";
        public const string BANNER_SEX = "{=Dramalord342}You were having intercourse with {ACTOR1.LINK}.";
        public const string BANNER_APPROACH_STOP = "{=Dramalord397}{ACTOR1.LINK} will not approach you again.";
        public const string BANNER_APPROACH_START = "{=Dramalord398}{ACTOR1.LINK} will approach you again.";
                    
        public const string RELATIONSHIP_FRIENDS = "{=Dramalord204}friends";
        public const string RELATIONSHIP_LOVERS = "{=Dramalord205}lovers";
        public const string RELATIONSHIP_MARRIED = "{=Dramalord206}married";
                      
        public static TextObject GetRelationshipStatusName(RelationshipType relation) => relation == RelationshipType.Spouse ? new(DramalordTexts.RELATIONSHIP_MARRIED) : (relation == RelationshipType.Lover) ? new(DramalordTexts.RELATIONSHIP_LOVERS) : new(DramalordTexts.RELATIONSHIP_FRIENDS);

    }
}
