using Dramalord.Conversations;
using Dramalord.UI;
using SandBox.GauntletUI.AutoGenerated0;
using System;
using System.Text.RegularExpressions;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ModuleManager;

namespace Dramalord.Notifications
{
    public enum InquiryContext
    {
        AcceptSex,
        Orphanize
    }

    public static class DramalordInquiry
    {
        public static void CreateYesNoInquiry(Hero actor1, string title, string text, Action yesAction, Action noAction) => CreateYesNoInquiry(actor1, new TextObject(title), new TextObject(text), yesAction, noAction);

        public static void CreateYesNoInquiry(Hero actor1, TextObject title, TextObject text, Action yesAction, Action noAction)
        {
            if(InformationManager.IsAnyInquiryActive())
            {
                return;
            }

            ConversationTools.SetCharacterObjects(text, actor1);

            InformationManager.ShowInquiry(
                    new InquiryData(
                        title.ToString(),
                        text.ToString(),
                        true,
                        true,
                        GameTexts.FindText("str_yes").ToString(),
                        GameTexts.FindText("str_no").ToString(),
                        () => { yesAction.Invoke(); /*Campaign.Current.SetTimeSpeed(speed);*/ },
                        () => { noAction.Invoke(); /*Campaign.Current.SetTimeSpeed(speed);*/ }
                        ), 
                    true,
                    true);
        }

        public static void CreateYesNoInquiry(Hero actor1, Hero actor2, TextObject title, TextObject text, Action yesAction, Action noAction)
        {
            if (InformationManager.IsAnyInquiryActive())
            {
                return;
            }

            ConversationTools.SetCharacterObjects(text, actor1, actor2);

            InformationManager.ShowInquiry(
                    new InquiryData(
                        title.ToString(),
                        text.ToString(),
                        true,
                        true,
                        GameTexts.FindText("str_yes").ToString(),
                        GameTexts.FindText("str_no").ToString(),
                        () => { yesAction.Invoke(); /*Campaign.Current.SetTimeSpeed(speed);*/ },
                        () => { noAction.Invoke(); /*Campaign.Current.SetTimeSpeed(speed);*/ }
                        ),
                    true,
                    true);
        }

        

        public static void CreateYesNoImageInquiry(Hero actor1, Hero actor2, TextObject text, Action yesAction, Action noAction, InquiryContext context)
        {
            ConversationTools.SetCharacterObjects(text, actor2);

            string basePath = ModuleHelper.GetModuleFullPath("Dramalord");
            string imagePath = System.IO.Path.Combine(basePath, "GUI", "Images", "inquiry");
            string fileName = "inquiry_";
            if (context == InquiryContext.AcceptSex)
            {
                fileName += "acceptsex_";
            }
            else if(context == InquiryContext.Orphanize)
            {
                fileName += "orphanize_";
            }

            if (actor1.IsFemale && actor2.IsFemale)
            {
                fileName += "f_f";
            }
            else if (!actor1.IsFemale && !actor2.IsFemale)
            {
                fileName += "m_m";
            }
            else if (actor1.IsFemale && !actor2.IsFemale)
            {
                fileName += "f_m";
            }
            else
            {
                fileName += "m_f";
            }

            fileName += ".jpg";

            imagePath = System.IO.Path.Combine(imagePath, fileName);
            string inquiryText = Regex.Replace(text.ToString(), @"<[^>]+>", "").Replace("&nbsp;", "").Replace("\t", "");
            ImageInquiryHelper.Show(imagePath, inquiryText, yesAction, noAction);
        }
    }
}
